In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import operator
import torch
import torch.nn as nn
import torch.optim as optim
import numpy as np
from sklearn.model_selection import train_test_split

In [3]:
df = pd.read_csv('dataset.csv')
df.head()

Disease   Symptom_1              Symptom_2              Symptom_3  \
0  Fungal infection     itching              skin_rash   nodal_skin_eruptions   
1  Fungal infection   skin_rash   nodal_skin_eruptions    dischromic _patches   
2  Fungal infection     itching   nodal_skin_eruptions    dischromic _patches   
3  Fungal infection     itching              skin_rash    dischromic _patches   
4  Fungal infection     itching              skin_rash   nodal_skin_eruptions   

              Symptom_4 Symptom_5 Symptom_6 Symptom_7 Symptom_8 Symptom_9  \
0   dischromic _patches       NaN       NaN       NaN       NaN       NaN   
1                   NaN       NaN       NaN       NaN       NaN       NaN   
2                   NaN       NaN       NaN       NaN       NaN       NaN   
3                   NaN       NaN       NaN       NaN       NaN       NaN   
4                   NaN       NaN       NaN       NaN       NaN       NaN   

  Symptom_10 Symptom_11 Symptom_12 Symptom_13 Symptom_14 Symptom_15  \
0        NaN        NaN        NaN        NaN        NaN        NaN   
1        NaN        NaN        NaN        NaN        NaN        NaN   
2        NaN        NaN        NaN        NaN        NaN        NaN   
3        NaN        NaN        NaN        NaN        NaN        NaN   
4        NaN        NaN        NaN        NaN        NaN        NaN   

  Symptom_16 Symptom_17  
0        NaN        NaN  
1        NaN        NaN  
2        NaN        NaN  
3        NaN        NaN  
4        NaN        NaN

In [4]:
df.shape

(4920, 18)

In [5]:
for j in range(df.shape[0]):
    for i in df.iloc[j,1:]:
        if pd.isna(i):
            continue
            

In [6]:
for i in df.iloc[0,1:]:
    if pd.isna(i):
        continue
    else:
        print(i)

itching
 skin_rash
 nodal_skin_eruptions
 dischromic _patches


In [7]:
freq = {}
for j in range(df.shape[0]):
    for i in df.iloc[j,1:]:
        if pd.isna(i):
            continue
        if i not in freq:
            freq[i] = 1
        else:
            freq[i] += 1
sort = dict(sorted(freq.items(),key=operator.itemgetter(1),reverse=True))
temp = list(dict(list(sort.items())[:10]).keys())
print(temp)

[' fatigue', ' vomiting', ' high_fever', ' loss_of_appetite', ' nausea', ' headache', ' abdominal_pain', ' yellowish_skin', ' yellowing_of_eyes', ' chills']


In [8]:
symp = []
for j in range(df.shape[0]):
    for i in df.iloc[j,1:]:
        if pd.isna(i):
            continue
        if i not in symp:
            symp.append(i)

In [9]:
diseases = []
for i in df['Disease']:
    if i not in diseases:
        diseases.append(i)
len(diseases)

41

In [10]:
dis = {}
for n, i in enumerate(symp):
    dis[i] = n
dis

{'itching': 0,
 ' skin_rash': 1,
 ' nodal_skin_eruptions': 2,
 ' dischromic _patches': 3,
 ' continuous_sneezing': 4,
 ' shivering': 5,
 ' chills': 6,
 ' watering_from_eyes': 7,
 ' stomach_pain': 8,
 ' acidity': 9,
 ' ulcers_on_tongue': 10,
 ' vomiting': 11,
 ' cough': 12,
 ' chest_pain': 13,
 ' yellowish_skin': 14,
 ' nausea': 15,
 ' loss_of_appetite': 16,
 ' abdominal_pain': 17,
 ' yellowing_of_eyes': 18,
 ' burning_micturition': 19,
 ' spotting_ urination': 20,
 ' passage_of_gases': 21,
 ' internal_itching': 22,
 ' indigestion': 23,
 ' muscle_wasting': 24,
 ' patches_in_throat': 25,
 ' high_fever': 26,
 ' extra_marital_contacts': 27,
 ' fatigue': 28,
 ' weight_loss': 29,
 ' restlessness': 30,
 ' lethargy': 31,
 ' irregular_sugar_level': 32,
 ' blurred_and_distorted_vision': 33,
 ' obesity': 34,
 ' excessive_hunger': 35,
 ' increased_appetite': 36,
 ' polyuria': 37,
 ' sunken_eyes': 38,
 ' dehydration': 39,
 ' diarrhoea': 40,
 ' breathlessness': 41,
 ' family_history': 42,
 ' mucoid_

In [11]:
X = []
dis = {}
for n, i in enumerate(symp):
    dis[i] = n
for j in range(df.shape[0]):
    temp = []
    for i in df.iloc[j,1:]:
        if pd.isna(i):
            continue
        else:
            temp.append(i)
    vector = [0] * len(symp)
    for i in temp:
        vector[dis[i]] = 1
    X.append(vector)
X = np.asarray(X)

In [12]:
y = []
for n, i in enumerate(diseases):
    dis[i] = n
for i, n in enumerate(df['Disease']):
    y.append(dis[n])
len(y)

4920

In [13]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.30)

In [14]:
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier(n_estimators = 10)  

clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)

from sklearn import metrics  
print()

print("ACCURACY OF THE MODEL: ", metrics.accuracy_score(y_test, y_pred))


ACCURACY OF THE MODEL:  1.0


In [15]:
from sklearn.naive_bayes import GaussianNB

GNB = GaussianNB()
y_pred = GNB.fit(X_train, y_train).predict(X_test)
print("Number of mislabeled points out of a total %d points : %d" % (X_test.shape[0], (y_test != y_pred).sum()))

Number of mislabeled points out of a total 1476 points : 0


In [17]:
y = []
dis = {}
for n, i in enumerate(diseases):
    dis[i] = n
for i in df['Disease']:
    vector = [0] * len(diseases)
    vector[dis[i]] = 1
    y.append(vector)
y = np.asarray(y)

In [18]:
freq = {}
for i in df['Disease']:
    if i not in freq:
        freq[i] = 1
    else:
        freq[i] += 1
freq

{'Fungal infection': 120,
 'Allergy': 120,
 'GERD': 120,
 'Chronic cholestasis': 120,
 'Drug Reaction': 120,
 'Peptic ulcer diseae': 120,
 'AIDS': 120,
 'Diabetes ': 120,
 'Gastroenteritis': 120,
 'Bronchial Asthma': 120,
 'Hypertension ': 120,
 'Migraine': 120,
 'Cervical spondylosis': 120,
 'Paralysis (brain hemorrhage)': 120,
 'Jaundice': 120,
 'Malaria': 120,
 'Chicken pox': 120,
 'Dengue': 120,
 'Typhoid': 120,
 'hepatitis A': 120,
 'Hepatitis B': 120,
 'Hepatitis C': 120,
 'Hepatitis D': 120,
 'Hepatitis E': 120,
 'Alcoholic hepatitis': 120,
 'Tuberculosis': 120,
 'Common Cold': 120,
 'Pneumonia': 120,
 'Dimorphic hemmorhoids(piles)': 120,
 'Heart attack': 120,
 'Varicose veins': 120,
 'Hypothyroidism': 120,
 'Hyperthyroidism': 120,
 'Hypoglycemia': 120,
 'Osteoarthristis': 120,
 'Arthritis': 120,
 '(vertigo) Paroymsal  Positional Vertigo': 120,
 'Acne': 120,
 'Urinary tract infection': 120,
 'Psoriasis': 120,
 'Impetigo': 120}

In [19]:
y

array([[1, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 1, 0, 0],
       [0, 0, 0, ..., 0, 1, 0],
       [0, 0, 0, ..., 0, 0, 1]])

In [20]:
count = 0
for i in X[0]:
    if i == 1:
        count += 1
count

4

In [31]:
# device = torch.device("mps")

class ChatBotModel(nn.Module):
    def __init__(self, input_size, hidden_size, output_size):
        super(ChatBotModel, self).__init__()
        self.fc1 = nn.Linear(input_size, hidden_size)
        self.relu1 = nn.Dropout(0.5)
        self.fc2 = nn.Linear(hidden_size, 128)
        self.relu2 = nn.Dropout(0.5)
        self.fc3 = nn.Linear(128, output_size)
        self.softmax = nn.Softmax(dim=1)

    def forward(self, x):
        x = torch.relu(self.fc1(x))
        x = self.relu1(x)
        x = torch.relu(self.fc2(x))
        x = self.relu2(x)
        x = self.fc3(x)
        x = self.softmax(x)
        return x

input_size = len(X[0])
hidden_size = 128
output_size = len(y[0])
model = ChatBotModel(input_size, hidden_size, output_size)

criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr = 0.005)

xtrain, xtest, ytrain, ytest = train_test_split(X, y, train_size = 0.8)

train_x = torch.Tensor(xtrain)
train_y = torch.Tensor([np.argmax(y) for y in ytrain])

num_epochs = 100

for epoch in range(num_epochs):
    batch_x = train_x
    batch_y = train_y
    optimizer.zero_grad()
    outputs = model(batch_x)

    loss = criterion(outputs, batch_y.long())
    loss.backward()
    optimizer.step()

    if epoch % 10 == 0:
        print(f'Epoch {epoch}, Loss: {loss.item()}')

torch.save(model.state_dict(), 'chatbotmodelnew.pth')


Epoch 0, Loss: 3.713451385498047
Epoch 10, Loss: 3.5938525199890137
Epoch 20, Loss: 3.3175458908081055
Epoch 30, Loss: 3.0817441940307617
Epoch 40, Loss: 2.916876792907715
Epoch 50, Loss: 2.868278741836548
Epoch 60, Loss: 2.859161138534546
Epoch 70, Loss: 2.8555705547332764
Epoch 80, Loss: 2.8544228076934814
Epoch 90, Loss: 2.8531224727630615


In [22]:
xtest.shape

(984, 131)

In [23]:
class ChatBotModel(nn.Module):
    def __init__(self, input_size, hidden_size, output_size):
        super(ChatBotModel, self).__init__()
        self.fc1 = nn.Linear(input_size, hidden_size)
        self.relu1 = nn.Dropout(0.5)
        self.fc2 = nn.Linear(hidden_size, 128)
        self.relu2 = nn.Dropout(0.5)
        self.fc3 = nn.Linear(128, output_size)
        self.softmax = nn.Softmax(dim=1)

    def forward(self, x):
        x = torch.relu(self.fc1(x))
        x = self.relu1(x)
        x = torch.relu(self.fc2(x))
        x = self.relu2(x)
        x = self.fc3(x)
        x = self.softmax(x)
        return x

In [24]:
input_size = len(X[0])
hidden_size = 128
output_size = len(y[0])
model = ChatBotModel(input_size, hidden_size, output_size)
model.load_state_dict(torch.load('chatbotmodelnew.pth'))

<All keys matched successfully>

In [29]:
from torchview import draw_graph

model_graph = draw_graph(ChatBotModel(131, 128, 41), input_size=(131,))

RuntimeError: Failed to run torchgraph see error message

In [30]:
from torchviz import make_dot

model = ChatBotModel()
y = model(X)

ValueError: source code string cannot contain null bytes

In [ ]:
from torchviz import make_dot

make_dot(yhat, params=dict(list(model.named_parameters()))).render("rnn_torchviz", format="png")

In [17]:
xtrain, xtest, ytrain, ytest = train_test_split(X, y, train_size = 0.8)

In [32]:
model.eval()
with torch.no_grad():
    ypred = model(torch.Tensor(xtest))
    acc = 0
    for i in range(len(xtest)):
        if np.argmax(ypred[i].tolist()) == np.argmax(ytest[i]):
            acc += 1
    print(acc / len(xtest))


0.8922764227642277


In [39]:
np.argmax(ypred[i].tolist())

16

In [ ]:
def get_active_symptoms():
    symptoms = []
    for j in range(df.shape[0]):
        for i in df.iloc[j,1:]:
            if pd.isna(i):
                continue
            if i not in symptoms:
                symptoms.append(i)
    formatted_symptoms = []
    for i in symptoms:
        formatted_symptoms.append(i.replace("_", " ").strip())
    dictionary_symptoms = {}
    for n, i in enumerate(formatted_symptoms):
        dictionary_symptoms[i] = n
    vector = [0] * len(formatted_symptoms)
    for i in active_symptoms:
        vector[dictionary_symptoms[i]] = 1
    return vector, dictionary_symptoms

In [ ]:
def diagnosis(vector, dictionary_symptoms):
    inverse = {}
    for key, value in dictionary_symptoms.items():
        inverse[value] = key
    model.eval()
    with torch.no_grad():
        ypred = model(torch.Tensor(torch.Tensor([vector])))
        for i in ypred.tolist():
            for j in i:
                if j > 0.01:
                    print(inverse[i.index(j)])

In [31]:
x = [' fatigue', ' cough', ' high_fever']
x = [' anxiety', ' obesity', ' malaise']
dis = {}
for n, i in enumerate(symp):
    dis[i] = n
vector = [0] * len(symp)
for i in x:
    vector[dis[i]] = 1

In [35]:
inverse = {}
for key, value in dis.items():
    inverse[value] = key

In [ ]:
diseases = []
for i in df['Disease']:
    if i not in diseases:
        diseases.append(i)
dictionary = {}
for n, i in enumerate(diseases):
    dictionary[i] = n

In [41]:
tr = model(torch.Tensor([vector]))
dictionary = {}
for n, i in enumerate(diseases):
    dictionary[i] = n
print(inverse[np.argmax(tr.tolist())])
for i in tr.tolist():
    for j in i:
        if j > 0.01:
            print(inverse[i.index(j)])

Hypoglycemia
Diabetes 
Pneumonia
Varicose veins
Hypoglycemia
Osteoarthristis


In [43]:
from sklearn import datasets  
iris = datasets.load_iris() 
X, y = datasets.load_iris( return_X_y = True)

In [47]:
X

array([[1, 1, 1, ..., 0, 0, 0],
       [0, 1, 1, ..., 0, 0, 0],
       [1, 0, 1, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 1, 0, ..., 0, 0, 0],
       [0, 1, 0, ..., 1, 1, 1]])

In [75]:
np.argmax(tr.tolist())

9

In [26]:
tr

tensor([[1.2448e-03, 3.4089e-06, 8.3435e-04, 4.2146e-07, 1.0435e-06, 4.2400e-06,
         1.4988e-04, 1.4994e-02, 8.8724e-04, 3.5845e-04, 2.6440e-05, 1.6855e-04,
         1.9007e-05, 1.3889e-05, 1.4789e-05, 3.0491e-04, 3.3344e-04, 1.7406e-04,
         1.7491e-05, 1.2299e-06, 1.2538e-04, 4.2968e-04, 1.0660e-05, 5.5083e-04,
         3.0612e-05, 7.6734e-05, 1.3958e-03, 3.8225e-02, 1.5970e-03, 1.8346e-06,
         5.0398e-02, 7.7265e-05, 4.8746e-04, 8.6535e-01, 2.0459e-02, 1.0831e-03,
         5.8717e-05, 1.9469e-07, 2.9672e-05, 5.2807e-05, 1.1839e-05]],
       grad_fn=<SoftmaxBackward0>)